### ISSUE TITLE
How to plot the output file "overlap.npz"?

### ISSUE THREAD

**Issue by TaoTaotheCreator** [nanotech-empa/cp2k-spm-tools#13]
Dear developers, I just compiled these codes on my computer and ran the examples in `/benzene_overlap`, and I got the output file `overlap.npz`. I want to get the image below (Nanoscale, 2021, 13, 1624–1628), but I do not know how to plot the` .npz` file. Could you please show me the way to get this kind of PDOS? Thank you!
![image](https://github.com/user-attachments/assets/f87b66e5-4b57-48b1-899d-e62fb5169ab8)

**Comment by eimrek** [comment]
hi @TaoTaotheCreator, thanks for the interest. The notebook https://github.com/nanotech-empa/cp2k-spm-tools/blob/master/overlap_viewer.ipynb should demonstrate a way to access and visualize the overlap.npz. Hope this helps! Closing for now, but feel free to re-open this issue if you run into problems or have other questions.

**Comment by TaoTaotheCreator** [comment]
Thanks! I have already got the `overlap.npz` running from the example `benzene_overlap`, and I tried to plot this outcome. The `overlap_viewer.ipynb` was converted to `overlap_viewer.py`, which was run in pycharm. However, the error came as below. Could you show me how to solve this? Thank you very much.
`D:\Anaconda3\python.exe F:/cp2k-spm-tools-master/overlap_viewer.py 
Traceback (most recent call last):
  File "F:\cp2k-spm-tools-master\overlap_viewer.py", line 74, in <module>
    for i_spin in range(len(d)):
TypeError: object of type 'NoneType' has no len()`
[inputfile.zip](https://github.com/user-attachments/files/17460630/inputfile.zip)

**Comment by TaoTaotheCreator** [comment]
Besides, when I ran the `run_overlap.sh` for my own systems, the error came as below:
`Traceback (most recent call last):
  File "../../overlap_from_wfns.py", line 151, in <module>
    mol_grid_orb.read_cp2k_input(args.cp2k_input_file2)
  File "/public4/home/sc53074/cp2k/LZH/cp2k-spm-tools-master/cp2k_spm_tools/cp2k_grid_orbitals.py", line 159, in read_cp2k_input
    raise ValueError("Cell is not rectangular")
ValueError: Cell is not rectangular`
Is there any requirement for the cell of slab and molecule model, respectively?

**Comment by eimrek** [comment]
Hi @TaoTaotheCreator. Sorry. the script do require modification for custom systems, but should give you an example to work with. Regarding the cell, unfortunately, yes, currently the library only supports rectangular cells.

**Comment by TaoTaotheCreator** [comment]
Okay, I plan to plot the PDOS using other approach. Thanks, eimrek!

**Comment by TaoTaotheCreator** [comment]
Yes, I see. But how to define the homo/lumo in this software? Because the lumo (94) in this legend is actually occupied by 1 electron in my gas-phase calculations. Besides, what’s the energy in the parenthesis? Does it refer to the Fermi energy calculated from the gas-phase calculations?

**Comment by TaoTaotheCreator** [comment]
Dear eimrek, could you please tell me the basic principle of PDOS overlap module? For example, how does the software identify the PDOS of molecule on substrates and its corresponding gas-phase orbital?  I don't need to know how the code works, I just want to know the general principle. Thanks!

**Comment by eimrek** [comment]
Hi, sure. The intended way to use the overlap module is as follows: you need to run CP2K calculation for 1) molecule adsorbed on slab; and 2) only molecule in the same geometrical conformation. Then, the module takes all Kohn-Sham orbitals of (2) and calculates overlaps (scalar products) with all kohn-sham orbitals of 1). This shows how much of 2) orbtials are included in each orbital of 1). And you can "broaden" the orbitals of 1) into a DoS, and also show the compositions in terms of molecular orbitals. Hope this makes sense.

**Comment by TaoTaotheCreator** [comment]
OK, I got it. Thank you : )
